CREATE TABLE IF NOT EXISTS firebase_users (
    firebase_uid TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY,
    email TEXT,
    display_name TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
